### ISSUE TITLE
error ModuleNotFoundError: No module named 'tomllib' (python 3.10)

### ISSUE THREAD

**Issue by BPie** [tedivm/paracelsus#10]
while using python 3.10, pip installs `paracelsus==0.5.0` . Running `pipenv run paracelsus graph` gives error
```python
ModuleNotFoundError: No module named 'tomllib'
```
tomllib is supported from 3.11. Maybe 'requires-python' should be specified or some other toml parser used.

**Comment by tedivm** [comment]
If you update to 0.5.1 you should be all set! Thanks for reporting!

**Comment by tedivm** [comment]
Note that I also updated the test suite so that 3.10, 3.11, and 3.12 are all tested on each PR so we shouldn't see any regressions.
